# Generated by Django 3.2.9 on 2021-11-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='userId',
        ),
    ]
